server:
  port: 8083
spring:
  application:
    name: AI-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness
      database: fitness
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    banner-mode: off

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
