server:
  port: 8082
spring:
  application:
    name: ACTIVITY-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness
      database: fitness
  main:
    banner-mode: off

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


