server:
  port: 8081
spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness
    username: postgres
    password: Eshwar@351
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  main:
    banner-mode: off

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

